#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
-------------------------------------------------------------------------
This file is part of the AgentSDK project.
Copyright (c) 2025 Huawei Technologies Co.,Ltd.

AgentSDK is licensed under Mulan PSL v2.
You can use this software according to the terms and conditions of the Mulan PSL v2.
You may obtain a copy of Mulan PSL v2 at:

         http://license.coscl.org.cn/MulanPSL2

THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
See the Mulan PSL v2 for more details.
-------------------------------------------------------------------------
"""
 
DEFAULT_CONFIG = {
    "actor_rollout_ref": {
        "actor": {
            "strategy": "fsdp",
            "ppo_mini_batch_size": 16,
            "ppo_micro_batch_size": None,
            "ppo_micro_batch_size_per_gpu": None,
            "use_dynamic_bsz": True,
            "ppo_max_token_len_per_gpu": 24000,
            "clip_ratio": 0.2,
            "clip_ratio_low": 0.2,
            "clip_ratio_high": 0.2,
            "policy_loss": {
                "loss_mode": "vanilla",
                "clip_cov_ratio": 0.0002,
                "clip_cov_lb": 1.0,
                "clip_cov_ub": 5.0,
                "kl_cov_ratio": 0.0002,
                "ppo_kl_coef": 0.1,
            },
            "clip_ratio_c": 3.0,
            "loss_agg_mode": "token-mean",
            "entropy_coeff": 0,
            "use_kl_loss": False,
            "use_torch_compile": True,
            "kl_loss_coef": 0.001,
            "kl_loss_type": "low_var_kl",
            "ppo_epochs": 1,
            "shuffle": False,
            "checkpoint": {
                "save_contents": ["model", "optimizer", "extra"],
                "load_contents": "${.save_contents}",
            },
            "optim": {
                "lr": 1.0e-06,
                "lr_warmup_steps_ratio": 0.0,
                "total_training_steps": -1,
                "weight_decay": 0.01,
                "lr_warmup_steps": -1,
                "min_lr_ratio": 0.0,
                "num_cycles": 0.5,
                "warmup_style": "constant",
            },
            "grad_clip": 1.0,
            "ulysses_sequence_parallel_size": 1,
            "entropy_from_logits_with_chunking": False,
            "entropy_checkpointing": False,
            "fsdp_config": {
                "wrap_policy": {"min_num_params": 0},
                "param_offload": False,
                "optimizer_offload": False,
                "offload_policy": False,
                "reshard_after_forward": True,
                "fsdp_size": -1,
                "forward_prefetch": False,
            },
        },
        "ref": {
            "strategy": "${actor_rollout_ref.actor.strategy}",
            "use_torch_compile": "${oc.select:actor_rollout_ref.actor.use_torch_compile,true}",
            "log_prob_micro_batch_size": None,
            "log_prob_micro_batch_size_per_gpu": None,
            "log_prob_use_dynamic_bsz": "${oc.select:actor_rollout_ref.actor.use_dynamic_bsz,false}",
            "log_prob_max_token_len_per_gpu": "${oc.select:actor_rollout_ref.actor.ppo_max_token_len_per_gpu,16384}",
            "fsdp_config": {
                "param_offload": True,
                "reshard_after_forward": True,
                "forward_prefetch": False,
                "wrap_policy": {"min_num_params": 0},
            },
            "ulysses_sequence_parallel_size": "${oc.select:actor_rollout_ref.actor.ulysses_sequence_parallel_size,1}",
            "entropy_from_logits_with_chunking": False,
            "entropy_checkpointing": False,
        },
        "rollout": {
            "name": "vllm",
            "mode": "async",
            "temperature": 0.6,
            "top_k": -1,
            "top_p": 1,
            "prompt_length": "${oc.select:data.max_prompt_length,512}",
            "response_length": "${oc.select:data.max_response_length,512}",
            "dtype": "bfloat16",
            "gpu_memory_utilization": 0.85,
            "ignore_eos": False,
            "enforce_eager": False,
            "free_cache_engine": True,
            "tensor_model_parallel_size": 4,
            "max_num_batched_tokens": 8192,
            "max_model_len": None,
            "max_num_seqs": 1024,
            "log_prob_micro_batch_size": None,
            "log_prob_micro_batch_size_per_gpu": None,
            "log_prob_use_dynamic_bsz": "${oc.select:actor_rollout_ref.actor.use_dynamic_bsz,false}",
            "log_prob_max_token_len_per_gpu": "${oc.select:actor_rollout_ref.actor.ppo_max_token_len_per_gpu,16384}",
            "disable_log_stats": True,
            "do_sample": True,
            "n": 2,
            "multi_stage_wake_up": False,
            "engine_kwargs": {
                "vllm": {"swap_space": None, "disable_mm_preprocessor_cache": False},
                "sglang": {"attention_backend": None},
            },
            "val_kwargs": {
                "top_k": -1,
                "top_p": 0.95,
                "temperature": 0.6,
                "n": 1,
                "do_sample": True,
            },
            "multi_turn": {
                "enable": False,
                "max_assistant_turns": None,
                "tool_config_path": None,
                "max_user_turns": None,
                "max_parallel_calls": 1,
                "max_tool_response_length": 256,
                "tool_response_truncate_side": "middle",
                "interaction_config_path": None,
                "completion_callback": None,
                "use_inference_chat_template": False,
                "tokenization_sanity_check_mode": "strict",
                "format": "hermes",
            },
            "calculate_log_probs": False,
            "agent": {
                "num_workers": 0,
                "agent_loop_config_path": None,
                "custom_async_server": {"path": None, "name": None},
            },
            "update_weights_bucket_megabytes": 512,
            "trace": {"backend": None, "token2text": False},
            "enable_chunked_prefill": True,
            "load_format": "dummy_dtensor",
            "layered_summon": False,
        },
        "hybrid_engine": True,
        "model": {
            "path": "~/home/models/Qwen2.5-7B-Instruct",
            "custom_chat_template": None,
            "use_shm": False,
            "external_lib": None,
            "override_config": {},
            "enable_gradient_checkpointing": True,
            "enable_activation_offload": False,
            "use_remove_padding": False,
            "lora_rank": 0,
            "lora_alpha": 16,
            "target_modules": "all-linear",
            "exclude_modules": None,
            "use_liger": False,
            "use_fused_kernels": False,
            "fused_kernel_options": {"impl_backend": "torch"},
            "trust_remote_code": False,
        },
        "profiler": {
            "_target_": "verl.utils.profiler.ProfilerConfig",
            "discrete": False,
            "all_ranks": False,
            "ranks": [],
        },
        "fsdp_config": {
            "param_offload": False,
            "optimizer_offload": False,
        },
    },
    "trainer": {
        "npu_profile": {
            "options": {
                "save_path": "./profiler_data",
                "level": "level1",
                "with_memory": False,
                "record_shapes": False,
                "with_npu": True,
                "with_cpu": True,
                "with_module": False,
                "with_stack": False,
                "analysis": True,
            }
        },
        "balance_batch": True,
        "total_epochs": 2,
        "total_training_steps": None,
        "profile_steps": None,
        "controller_nsight_options": {
            "trace": "cuda,nvtx,cublas,ucx",
            "cuda-memory-usage": "true",
            "cuda-graph-trace": "graph",
        },
        "worker_nsight_options": {
            "trace": "cuda,nvtx,cublas,ucx",
            "cuda-memory-usage": "true",
            "cuda-graph-trace": "graph",
            "capture-range": "cudaProfilerApi",
            "capture-range-end": None,
            "kill": "none",
        },
        "project_name": "deepscaler-agent",
        "experiment_name": "deepscaler-math-debug-sync",
        "logger": ["console"],
        "log_val_generations": 0,
        "rollout_data_dir": None,
        "validation_data_dir": None,
        "nnodes": 1,
        "n_gpus_per_node": 8,
        "save_freq": 10,
        "esi_redundant_time": 0,
        "resume_mode": "auto",
        "resume_from_path": None,
        "val_before_train": True,
        "val_only": False,
        "test_freq": 10,
        "critic_warmup": 0,
        "default_hdfs_dir": None,
        "del_local_ckpt_after_load": False,
        "default_local_dir": "checkpoints/${trainer.project_name}/${trainer.experiment_name}",
        "max_actor_ckpt_to_keep": None,
        "max_critic_ckpt_to_keep": None,
        "ray_wait_register_center_timeout": 300,
        "device": "npu",
        "use_legacy_worker_impl": "auto",
    },
    "data": {
        "tokenizer": None,
        "use_shm": False,
        "train_files": "~/home/datasets/gsm8k/train.parquet",
        "val_files": "~/home/datasets/gsm8k/test.parquet",
        "prompt_key": "prompt",
        "reward_fn_key": "data_source",
        "max_prompt_length": 2048,
        "max_response_length": 2048,
        "train_batch_size": 8,
        "val_batch_size": 512,
        "return_raw_input_ids": False,
        "return_raw_chat": False,
        "return_full_prompt": False,
        "shuffle": True,
        "dataloader_num_workers": 8,
        "validation_shuffle": False,
        "filter_overlong_prompts": False,
        "filter_overlong_prompts_workers": 1,
        "truncation": "error",
        "image_key": "images",
        "video_key": "videos",
        "trust_remote_code": False,
        "custom_cls": {"path": None, "name": None},
        "return_multi_modal_inputs": True,
        "sampler": {"class_path": None, "class_name": None},
        "datagen": {"path": None, "name": None},
    },
    "critic": {
        "rollout_n": "${oc.select:actor_rollout_ref.rollout.n,1}",
        "strategy": "fsdp",
        "optim": {
            "lr_warmup_steps_ratio": 0.0,
            "total_training_steps": -1,
            "weight_decay": 0.01,
            "lr": 1.0e-05,
            "min_lr_ratio": None,
            "warmup_style": "constant",
        },
        "model": {
            "path": "~/models/deepseek-llm-7b-chat",
            "tokenizer_path": "${oc.select:actor_rollout_ref.model.path,\"~/models/deepseek-llm-7b-chat\"}",
            "override_config": {},
            "external_lib": "${oc.select:actor_rollout_ref.model.external_lib,null}",
            "trust_remote_code": "${oc.select:actor_rollout_ref.model.trust_remote_code,false}",
            "use_shm": False,
            "enable_gradient_checkpointing": True,
            "enable_activation_offload": False,
            "use_remove_padding": False,
            "fsdp_config": {
                "param_offload": False,
                "optimizer_offload": False,
                "offload_policy": False,
                "reshard_after_forward": True,
                "wrap_policy": {"min_num_params": 0},
                "fsdp_size": -1,
                "forward_prefetch": False,
            },
            "lora_rank": 0,
            "lora_alpha": 16,
            "target_modules": "all-linear",
        },
        "ppo_mini_batch_size": "${oc.select:actor_rollout_ref.actor.ppo_mini_batch_size,256}",
        "ppo_micro_batch_size": None,
        "ppo_micro_batch_size_per_gpu": "${oc.select:.ppo_micro_batch_size,null}",
        "use_dynamic_bsz": "${oc.select:actor_rollout_ref.actor.use_dynamic_bsz,false}",
        "ppo_max_token_len_per_gpu": 32768,
        "forward_max_token_len_per_gpu": "${.ppo_max_token_len_per_gpu}",
        "ppo_epochs": "${oc.select:actor_rollout_ref.actor.ppo_epochs,1}",
        "shuffle": "${oc.select:actor_rollout_ref.actor.shuffle,false}",
        "cliprange_value": 0.5,
        "loss_agg_mode": "${oc.select:actor_rollout_ref.actor.loss_agg_mode,token-mean}",
        "checkpoint": {
            "save_contents": ["model", "optimizer", "extra"],
            "load_contents": "${.save_contents}",
        },
        "profiler": {
            "_target_": "verl.utils.profiler.ProfilerConfig",
            "discrete": False,
            "all_ranks": False,
            "ranks": [],
        },
        "_target_": "verl.trainer.config.FSDPCriticConfig",
        "forward_micro_batch_size": "${oc.select:.ppo_micro_batch_size,null}",
        "forward_micro_batch_size_per_gpu": "${oc.select:.ppo_micro_batch_size_per_gpu,null}",
        "ulysses_sequence_parallel_size": 1,
        "grad_clip": 1.0,
    },
    "reward_model": {
        "enable": False,
        "strategy": "fsdp",
        "model": {
            "input_tokenizer": "${actor_rollout_ref.model.path}",
            "path": "~/models/FsfairX-LLaMA3-RM-v0.1",
            "external_lib": "${actor_rollout_ref.model.external_lib}",
            "trust_remote_code": False,
            "use_shm": False,
            "use_remove_padding": False,
            "use_fused_kernels": "${actor_rollout_ref.model.use_fused_kernels}",
            "fsdp_config": {
                "wrap_policy": {"min_num_params": 0},
                "param_offload": False,
                "reshard_after_forward": True,
                "fsdp_size": -1,
                "forward_prefetch": False,
            },
        },
        "micro_batch_size": None,
        "micro_batch_size_per_gpu": None,
        "max_length": None,
        "use_dynamic_bsz": "${critic.use_dynamic_bsz}",
        "forward_max_token_len_per_gpu": "${critic.forward_max_token_len_per_gpu}",
        "reward_manager": "naive",
        "launch_reward_fn_async": False,
        "sandbox_fusion": {
            "url": None,
            "max_concurrent": 64,
            "memory_limit_mb": 1024,
        },
        "profiler": {
            "_target_": "verl.utils.profiler.ProfilerConfig",
            "discrete": False,
            "all_ranks": False,
            "ranks": [],
        },
        "ulysses_sequence_parallel_size": 1,
    },
    "custom_reward_function": {"path": None, "name": "compute_score"},
    "algorithm": {
        "_target_": "verl.trainer.config.AlgoConfig",
        "gamma": 1.0,
        "lam": 1.0,
        "adv_estimator": "grpo",
        "norm_adv_by_std_in_grpo": True,
        "use_kl_in_reward": False,
        "kl_penalty": "kl",
        "kl_ctrl": {
            "_target_": "verl.trainer.config.KLControlConfig",
            "type": "fixed",
            "kl_coef": 0.001,
            "horizon": 10000,
            "target_kl": 0.1,
        },
        "use_pf_ppo": False,
        "pf_ppo": {
            "_target_": "verl.trainer.config.PFPPOConfig",
            "reweight_method": "pow",
            "weight_pow": 2.0,
        },
    },
    "ray_init": {"num_cpus": None, "timeline_json_file": None},
}