input: /home/w00610567/dataset/cs/transformed/
tokenizer_name_or_path: /opt/DPC/models/l00619320/weights/Qwen2.5-7B-Instruct/
output_prefix: /opt/DPC/models/w00610567/dataset/cs/large/rl
handler_name: R1AlpacaStyleInstructionHandler
tokenizer_type: HuggingFaceTokenizer
workers: 8
log_interval: 1000
prompt_type: qwq
dataset_additional_keys: [labels, log_data]
map_keys: {"query":"", "response":"answer", "prompt": "question"}