tokenizer_name_or_path: /path/to/tokenizer
data_path: /path/to/dataset
load_params_path: /path/to/model/params
save_params_path: /path/to/save/model/params
train_iters: 1
agent_name: test_agent
agent_engine_wrapper_path: /path/to/agent/engine/wrapper
