# =============================================================
# Agentic RL提供两种运行模式：
# 1. SERVE MODE     服务化部署，提供 HTTP/HTTPS 访问能力（如：多轮对话、模型推理等）
# 2. DIRECT MODE    直连模式，提供单次 JOB 执行能力（如：单次训练作业等）
# =============================================================
agentic_ai:
  mode: serve # 模式选择：serve | direct
  log_level: DEBUG
  log_dir: /var/log/

serve_conf:
  host: 0.0.0.0
  port: 8030

direct_conf:
  entrypoints:
    - job_type: train
      job_name: ""
      job_kwargs: { }

# =============================================================
# Train 预定义任务：
# 1. 预定义任务包括采用RL框架类型、参数等等，初始化时占用资源，触发后开始训练（支持开始、暂停、取消）
# 2. SERVE 模式下，预定义任务列表默认为空; DIRECT 模式下，初始化任务等待触发训练（触发：direct_conf.entrypoints）
# =============================================================
train_instances: [ ]


# =============================================================
# Agent 预置服务：
# 1. 提供如：Math / WebSearch 等智能体对话服务
# =============================================================
agent_instances: [ ]


# =============================================================
# Infer 预置服务：
# 1. 提供如：QWen / Deepseek 等大模型推理服务
# 2. 提供 OpenAI Chat 推理接口
# =============================================================
pd_mode: false # true 表示 PD 分离模式，false 表示混部模式

# 以下为混部模式参数
infer_instances:
  - name: Qwen3-235B-BF16
    executor_num: 1
    executor_kwargs:
      # 以下参数为 InferExecutor 初始化参数
      engine: vllm_mp
      engine_kwargs:
        # 以下参数为 vLLMInferServer 初始化参数
        host: 0.0.0.0
        port: 8333
        model_name: Qwen3-235B-BF16
        model: /opt/DPC/models/l30060498/models/Qwen3-235B-BF16
        tensor_parallel_size: 8
        data_parallel_size: 2
        data_parallel_size_local: 1
        data_parallel_rpc_port: 13389
        enable_expert_parallel: True
        gpu_memory_utilization: 0.8
        max_model_len: 8192
        enable_prefix_caching: True
        trust_remote_code: True
        distributed_executor_backend: mp
    resource_info:
      - NPU: 8
      - NPU: 8