defaults:
  - model:
      - qwen25_7b

megatron_training:
  model: qwen25_7b
  use_fused_rmsnorm: true
  use_mcore_models: true
  sequence_parallel: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: ${REQUIRED_VALUE}
  global_batch_size: 2
  seq_length: 8192
  save_interval: 1000
  train_iters: 10
  stage: ray_grpo
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  norm_epsilon: 1e-6
  dataset_additional_keys: []
  data_path: ${REQUIRED_VALUE}
  split: 100,0,0 # only for train
  reset_position_ids: true

actor_config:
  model: qwen25_7b
  micro_batch_size: 1
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 1
  lr: 1e-7
  lr_decay_style: constant
  min_lr: 0.0
  weight_decay: 0.0
  lr_warmup_fraction: 0.0
  clip_grad: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  initial_loss_scale: 4096
  finetune: true
  load: ${REQUIRED_VALUE}
  save: ${REQUIRED_VALUE}
  no_load_optim: true
  no_load_rng: true

rl_config:
  use_remove_padding: true
  use_integrated_worker: true
  guarantee_order: false
  blocking: false
  gamma: 1.0
  lam: 0.95
  adv_estimator: group_norm
  kl_penalty: kl
  kl_ctrl_type: fixed
  init_kl_coef: 0.05
  mini_batch_size: 16
  max_prompt_length: 8192
  epochs: 1
  clip_ratio: 0.2
  entropy_coeff: 0.0
  shuffle_mini_batch: false
  n_samples_per_prompt: 2
  actor_rollout_dispatch_size: 2  # Generation global_batch_size * n_samples // data_parallel must be divisible by micro_batch_size
  rule_reward: true
  verifier_function: ["env_reward"]  # 修改
  verifier_weight: [1.0]
  verifier_parallel: 1
  verifier_timeout: 300
  use_tensorboard: true
  simplify_think_content: false
  test_before_train: false
  test_only:  false # only run test data
  validate_n_samples: 1 # 测试时轨迹采样次数
  validate_freq: 1  # frequency for validation
  validate_num_samples: 5 # 从test数据集中顺序切分

  actor_resource:
    num_npus: 4

generate_config:
  enforce_eager: true
  # tokenizer相关配置
  trust_remote_code: true

  # 推理时的并行配置
  infer_tensor_parallel_size: 4
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 1

  # vllm 模型相关设置
  enable_sleep_mode: true
  load_format: megatron
  max_num_seqs: 32
  max_model_len: 16384
  max_num_batched_tokens: 16384
  dtype: "bfloat16"
  gpu_memory_utilization: 0.4

  offload_train_optimizer: true
  offload_train_grad: true
  offload_train_param: true

  # infer engine backend配置
  infer_backend: vllm

  # agent execution配置
  base_url: DEPRECATED_VALUE
  api_key: DEPRECATED_VALUE
  train_backend: mindspeed_rl
  agent_engine: DEPRECATED_VALUE

  # 采样配置
  sampling_config:
    logprobs: 1
    max_tokens: 8192
    top_p: 0.9
    top_k: 50
    min_p: 0.01
    temperature: 0.9
    detokenize: false

  validate_sampling:
    max_tokens: 8192
    top_p: 0.5
    top_k: 50
    min_p: 0.01
    temperature: 0.2

  # one step off配置
  init_num_group_batches: 1
  max_queue_size: 6
  weight_save_dir: ${REQUIRED_VALUE}
  update_weights_interval: 1
  ckpt_delta: 4
  data_optimized: false

agentic_env_config:
  namespace: agentic_raygroup
  max_steps: 1
  max_tool_length: 8192
  agent_name: DEPRECATED_VALUE
  tool_url: DEPRECATED_VALUE