defaults:
  - model:
      - qwen25_32b

megatron_training:
  model: qwen25_32b
  use_fused_rmsnorm: true
  use_mcore_models: true
  sequence_parallel: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: /opt/DPC/models/l00619320/weights/Qwen-QWQ-32B
  global_batch_size: 2
  seq_length: 4096
  save_interval: 1000
  train_iters: 1000
  stage: ray_grpo
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  norm_epsilon: 1e-6
  dataset_additional_keys: ['labels', 'seq']
  data_path: /opt/DPC/models/l00619320/datasets/ioh0704/rl
  split: 100,0,0

actor_config:
  model: qwen25_32b
  micro_batch_size: 1
  tensor_model_parallel_size: 8
  pipeline_model_parallel_size: 2
  lr: 1e-7
  lr_decay_style: constant
  min_lr: 0.0
  weight_decay: 0.0
  lr_warmup_fraction: 0.0
  clip_grad: 10000.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  initial_loss_scale: 4096
  finetune: true
  load: /opt/DPC/models/w00623271/original_ckpts/Qwen_QWQ-32B-tp8pp2/
  save: /opt/DPC/models/l00619320/temp/qwq32b/save_ckpt/
  no_load_optim: true
  no_load_rng: true

ref_config:
  model: qwen25_32b
  tensor_model_parallel_size: 8
  pipeline_model_parallel_size: 1
  micro_batch_size: 1
  load: /opt/DPC/models/w00623271/original_ckpts/Qwen_QWQ-32B-tp8pp1/
  no_load_optim: true
  no_load_rng: true

reward_config:
  model: qwen25_32b
  micro_batch_size: 1


rl_config:
  use_integrated_worker: false
  guarantee_order: false
  blocking: true
  gamma: 1.0
  lam: 0.95
  adv_estimator: group_norm
  kl_penalty: kl
  kl_ctrl_type: fixed
  init_kl_coef: 0.05
  mini_batch_size: 2
  max_prompt_length: 4096
  epochs: 1
  clip_ratio: 0.2
  entropy_coeff: 0.001
  shuffle_mini_batch: false
  n_samples_per_prompt: 2
  actor_rollout_dispatch_size: 2
  rule_reward: true
  verifier_function: ["env_reward"]  # 修改
  verifier_weight: [1.0]
  verifier_parallel: 1
  verifier_timeout: 300
  use_tensorboard: true
  simplify_think_content: false
  actor_resource:
    num_npus: 16
  reference_resource:
    num_npus: 8

generate_config:
  enforce_eager: true
  trust_remote_code: true

  # 推理时的并行配置
  infer_tensor_parallel_size: 8
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 1

  # vllm 模型相关设置
  enable_sleep_mode: false
  load_format: megatron
  max_num_seqs: 8
  max_model_len: 4096
  max_num_batched_tokens: 4096
  dtype: "bfloat16"
  gpu_memory_utilization: 0.3

  offload_train_optimizer: true
  offload_train_grad: true
  offload_train_param: true

  # agent execution配置
  base_url: http:xxx
  api_key: empty
  train_backend: mindspeed_rl

  # 采样配置
  sampling_config:
    logprobs: 1
    max_tokens: 128
    top_p: 0.9
    top_k: 50
    min_p: 0.01
    temperature: 0.9
    detokenize: false

agentic_env_config:
  namespace: agentic_raygroup
  agent_name: dtn
  tool_url: http://10.44.101.61:5005/rca/train/