defaults:
  - model:
      - qwen3_235b

megatron_training:
  model: qwen3_235b
  use_fused_rmsnorm: true
  use_mcore_models: true
  sequence_parallel: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  moe_alltoall_overlap_comm: true
  shape_order: BNSD
  bf16: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: /home/ma-user/modelarts/inputs/qwen_model_url_1/  # 模型tokenizer路径
  global_batch_size: 64
  seq_length: 20480
  save_interval: 1000
  train_iters: 200
  stage: ray_grpo
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  norm_epsilon: 1e-6
  dataset_additional_keys: ['labels', 'content']  #根据工具修改
  data_path: /home/ma-user/modelarts/inputs/data_url_0/rl  # 数据集路径
  split: 100,0,0
  swap_optimizer: true
  reset_position_ids: true
  swap_attention: true  # 性能优化参数
  use_fused_ring_attention_update: true
  use_cp_send_recv_overlap: true

actor_config:
  model: qwen3_235b
  micro_batch_size: 1
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 16
  noop_layers: "5,95"
  num_layers: 96
  expert_model_parallel_size: 4

  context_parallel_size: 4  # dp=总卡数/tp/pp cp要被dp整除 dp/cp要能整除 模为0
  context_parallel_algo: megatron_cp_algo
  cp_attention_mask_type: causal
  reset_attention_mask: true

  lr: 1e-6
  lr_decay_style: constant
  min_lr: 0.0
  weight_decay: 0.0
  lr_warmup_fraction: 0.0
  clip_grad: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95
  initial_loss_scale: 4096
  finetune: true
  load: /models/g00898995/model/Qwen3-235B-thinking-2507-tp2pp16ep4/  # tp2pp16ep4切分权重路径
  save: ./ckpt
  no_load_optim: true
  no_load_rng: true
  no_save_optim: true

  moe_tp_extend_ep: true
  gemm_gradient_accumulation_fusion: true
  recompute_granularity: full
  recompute_method: block
  recompute_num_layers: 6  # 总层数/pipeline_model_parallel_size=96/16=6
  no_shuffle: true

rl_config:
  use_dynamic_bsz: true
  max_packing_token_size: 40960  # 65536可能OOM 40K+seqlen_balancing_opt.py优化
  use_remove_padding: true
  use_integrated_worker: true
  ref_forward_micro_batch_size: 2
  actor_forward_micro_batch_size: 2
  guarantee_order: false
  blocking: true
  gamma: 1.0
  lam: 0.95
  adv_estimator: group_norm
  kl_penalty: low_var_kl
  kl_ctrl_type: fixed
  init_kl_coef: 0.001
  mini_batch_size: 64  # 与global_batch_size一致
  max_prompt_length: 40960  # user_prompt长度
  epochs: 1
  clip_ratio: 0.2
  entropy_coeff: 0.0
  shuffle_mini_batch: false
  n_samples_per_prompt: 8
  actor_rollout_dispatch_size: 8  # 最大是总样本数16*8/推理实例数2 且是n_samples_per_prompt的倍数
  rule_reward: true
  verifier_function: ["env_reward"]  # 根据工具修改
  verifier_weight: [1.0]
  verifier_parallel: 1
  verifier_timeout: 600
  use_tensorboard: true
  simplify_think_content: false
  actor_resource:
    num_npus: 256  # 推理需要的

generate_config:
  enforce_eager: false
  trust_remote_code: true
  enable_expert_parallel: true

  # 推理时的并行配置
  enable_sleep_mode: true #单轮无
  load_format: megatron #单轮无
  infer_tensor_parallel_size: 4 #4
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 8 # 注意：需要修改runtime_env.yaml中的VLLM_DP_SIZE: '8'

  # vllm 模型相关设置
  enable_prefix_caching: true
  max_num_seqs: 8
  max_model_len: 65536
  max_num_batched_tokens: 8192  #可以配合gpu_memory_utilization改 这样num_seqs可以调大
  dtype: "bfloat16"
  gpu_memory_utilization: 0.7

  offload_train_optimizer: false
  offload_train_grad: true
  offload_train_param: true

  # infer engine backend配置
  infer_backend: vllm

  # agent execution配置
  base_url: http:xxx
  api_key: empty
  train_backend: mindspeed_rl
  agent_engine: rllm

  # 采样配置
  sampling_config:
    logprobs: 1
    max_tokens: 16384
    top_p: 0.9
    top_k: 50
    min_p: 0.01
    temperature: 0.9
    detokenize: false

  # on policy配置
  init_num_group_batches: 1 #2  # 初始发送rollout的数据量 应 >= hybrid_batch_num
  max_queue_size: 6  # rollout接收数据队列大小 不能 < hybrid_batch_num
  hybrid_batch_num: 1 #2  # 开启rollout混合批次 1表示不开启
  enable_version_control: true  # 开启rollout权重更新版本控制 同时修改runtime_env的WAIT_AVAILABLE_WEIGHT_TIMEOUT: 'None'
  weight_save_dir: /models/qwen3_235b_tp2pp16ep4  # 临时权重保存路径 注意: 不能重复
  update_weights_interval: 1  # 默认train更新每一版权重
  ckpt_delta: 2  # 控制目录的权重缓存总数 节约磁盘占用空间
  data_optimized: false
  use_on_policy: true  # false：开启on_policy  默认true: 开启off_policy

agentic_env_config: # 注意: 部分参数会被外层yaml覆盖
  namespace: agentic_raygroup
  agent_name: dtn_code
  max_steps: 10
  tool_url: /home/ma-user/modelarts/inputs/tool_url_2  # 根据工具修改
  rollout_output_path: /home/ma-user/modelarts/outputs/train_url_0/  # 轨迹输出路径
  tool_timeout: 20  # 工具调用超时设置
  trajectory_timeout: 15000  # 轨迹超时截断设置 缺少请求超时设置配置